# Generated by Django 5.2.4 on 2025-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UZS', 'uzb uzs')], max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
    ]
