# Generated by Django 5.2.4 on 2025-07-31 06:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America')], default='Europe', max_length=255)),
                ('description', models.TextField()),
                ('start_point', models.CharField(default='Tashkent', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(choices=[('7_days', '7_days'), ('14_days', '14_days'), ('1_month', '1_month')], default='14_days', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_children', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_seats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('departure_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='UserTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('has_attended', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourdestination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tours',
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
