# Generated by Django 5.2.4 on 2025-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourdestination_images_tourdestination_includes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdestination',
            name='location',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('NORTH_AMERICA', 'North America'), ('South America', 'South America')], default='Europe', max_length=255),
        ),
    ]
