# Generated by Django 5.2.4 on 2025-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourdestination_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='booking_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usertour',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertour',
            name='payment_method',
            field=models.CharField(choices=[('PAYME', 'Payme'), ('CLICK', 'Click'), ('CASH', 'Cash')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='duration',
            field=models.CharField(choices=[('7_DAYS', '7_days'), ('14_DAYS', '14_days'), ('1_MONTH', '1_month')], default='14_DAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='location',
            field=models.CharField(choices=[('EUROPE', 'Europe'), ('ASIA', 'Asia'), ('NORTH_AMERICA', 'North America'), ('SOUTH_AMERICA', 'South America')], default='Europe', max_length=255),
        ),
        migrations.AlterField(
            model_name='usertour',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
