# Generated by Django 5.2.4 on 2025-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_usertour_booking_code_usertour_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdestination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
