# Generated by Django 5.2.4 on 2025-07-31 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('tours', '0005_tourdestination_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdestination',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency'),
        ),
    ]
