# Generated by Django 5.2.4 on 2025-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourdestination_is_hot_tourpricewatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdestination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
