# Generated by Django 5.2.4 on 2025-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
