# Generated by Django 5.2.4 on 2025-07-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0003_alter_tourdestination_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_full', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_schedules', to='tours.tourdestination')),
            ],
            options={
                'db_table': 'tour_schedules',
            },
        ),
    ]
