# Generated by Django 5.2.4 on 2025-08-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
